[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/gerenciar"
  to = "/gerenciar.html"
  status = 200

# ADICIONE ESTA NOVA REGRA
[[redirects]]
  from = "/galeria"
  to = "/galeria.html"
  status = 200
