# Configuração de Construção Explícita
[build]
  # Diz à Netlify que os arquivos do seu site estão na pasta principal
  publish = "." 
  # Diz à Netlify onde encontrar a pasta do seu "cofre" (as funções)
  functions = "netlify/functions"

# Regra de Redirecionamento (O "Atalho" Inteligente e Seguro)
[[redirects]]
  # Qualquer chamada para /api/alguma-coisa...
  from = "/api/*"
  # ...será levada para a cozinha correta.
  to = "/.netlify/functions/:splat"
  # Status 200 faz isso funcionar como um "proxy".
  status = 200
