backend:
  name: github
  repo: guilhermeprogam12/Jornal7A
  branch: main
  
# Isso é importante para o login funcionar melhor com o GitHub Pages
publish_mode: editorial_workflow

# Onde as imagens que você subir pelo CMS serão salvas
media_folder: "assets/images"
public_folder: "/assets/images"

# Coleções de conteúdo (nosso jornal)
collections:
  - name: "noticias"
    label: "Notícias"
    folder: "_noticias" # As notícias serão salvas em uma nova pasta _noticias
    create: true
    slug: "{{fields.title}}"
    fields:
      - { label: "Título da Notícia", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Categoria", name: "category", widget: "string", default: "Geral" }
      - { label: "Corpo da Notícia", name: "body", widget: "markdown" }
