backend:
  name: github
  repo: guilhermeprogam12/Jornal7A
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"
# ... e o resto do código
